services:

  postgres:
    image: postgres:17.10
    container_name: pg_user_service

    environment:
      POSTGRES_DB: user-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper

    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

    ports:
      - "2181:2181"


  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka

    depends_on:
      - zookeeper

    ports:
      - "9092:9092"

    environment:

      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # ВНУТРЕННИЙ listener (для docker сети)
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092

      # как видят клиенты
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT

      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


  schema-registry:
    image: confluentinc/cp-schema-registry:7.6.0
    container_name: schema-registry

    depends_on:
      - kafka

    ports:
      - "8081:8081"

    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry

      # внутри docker сети
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092

      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081


  mailhog:
    image: mailhog/mailhog
    container_name: mailhog

    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  postgres_data:
