spring.application.name=user-service

# DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/user-service
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Hibernate
spring.jpa.properties.hibernate.format_sql=true

# SQL init
spring.sql.init.mode=never